// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at ۱۴۰۴/۴/۳۰, ۱۳:۵۶:۲۷
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/project/vue/tailwind-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/vue/tailwind-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/vue/tailwind-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/vue/tailwind-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/vue/tailwind-nuxt/plugins/**/*.{js,ts,mjs}","C:/project/vue/tailwind-nuxt/composables/**/*.{js,ts,mjs}","C:/project/vue/tailwind-nuxt/utils/**/*.{js,ts,mjs}","C:/project/vue/tailwind-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/vue/tailwind-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/project/vue/tailwind-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/project/vue/tailwind-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;